language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.0"
branches:
  only:
    - master
    - future
notifications:
    email:
        on_failure: always
        on_success: never
script: python paperwork.py
