language: python
python:
    - "3.4"
    - "3.3"
branches:
  only:
    - master
    - development
notifications:
    email:
        on_failure: always
        on_success: never
install:
    - "pip install -r requirements.txt"
    - "pip install ."
script: python -m unittest discover
