language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
branches:
  only:
    - master
    - development
notifications:
    email:
        on_failure: change
        on_success: never
install:
    - "pip install ."
script: python -m unittest discover
